---
development:
  DB_KEY: eIt3pxQMCtQUxv6KcQ4T9wfQmOlYmNrUwrgSC9bfbH4=
  MSG_KEY: <`rake new_key:msg`>
  MAILGUN_API_KEY: <provision through Heroku or Mailgun>
  DATABASE_URL: sqlite://app/db/store/development.db
  SECURE_SCHEME: HTTP

test:
  DB_KEY: eIt3pxQMCtQUxv6KcQ4T9wfQmOlYmNrUwrgSC9bfbH4=
  MSG_KEY: <`rake new_key:msg`>
  AILGUN_API_KEY: <provision through Heroku or Mailgun>
  DATABASE_URL: sqlite://app/db/store/test.db
  SECURE_SCHEME: HTTP

production:
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  DATABASE_URL: <set to production DB>
  SECURE_SCHEME: HTTPS