---
development:
  SECURE_SCHEME: HTTP
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: eIt3pxQMCtQUxv6KcQ4T9wfQmOlYmNrUwrgSC9bfbH4=
  MSG_KEY: Szdo9JA1Gzdbiy17/BX5ajwIkk9U7ZVOnYBzzbO9x0A=
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: borhanlee10@gmail.com
  GITHUB_ACCOUNT_URL: https://api.github.com/user


test:
  SECURE_SCHEME: HTTP
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: eIt3pxQMCtQUxv6KcQ4T9wfQmOlYmNrUwrgSC9bfbH4=
  MSG_KEY: Szdo9JA1Gzdbiy17/BX5ajwIkk9U7ZVOnYBzzbO9x0A=
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
  SENDGRID_FROM_EMAIL: borhanLee10@gmail.com
  GITHUB_ACCOUNT_URL: https://api.github.com/user

production:
  SECURE_SCHEME: HTTPS
  DATABASE_URL: sqlite://app/db/store/development.db
  MSG_KEY: Szdo9JA1Gzdbiy17/BX5ajwIkk9U7ZVOnYBzzbO9x0A=
  DB_KEY: <`rake new_key:db`>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  GITHUB_ACCOUNT_URL: https://api.github.com/user
